### ISSUE TITLE
CK.Text portability

### ISSUE THREAD

**Issue by Martz94** [Invenietis/ck-core#24]
Hello,

I got this error when trying to reference CK.Core 5.0.0 (and therefore CK.Text) from a PCL library project:

`Could not install package 'CK.Text 5.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Is there any special reason why CK.Text is not portable?

**Comment by olivier-spinelli** [comment]
There should be one and only one reason for this: we stopped multi-targeting currently because of the mess it is…
We planned to use new Core with its project.json to easily support multi-targeting.
Currently, with standard csproj, it is not that easy since we often need to maintain multiple csproj (with aliased files in them). We did this for .Net4 and .Net45 and stopped…

That said, nothing should prevent the CK-Text to run on portable…
It is so simple that there is a chance that a simple change in the CodeCakeBuilder build chain suffice...

**Comment by Martz94** [comment]
Ok I'll investigate. Thanks.
